// GENERATED by app/tools/generate-protocol.mjs - do not edit.
//
// The message layout is defined once, in the firmware headers, and this file
// is derived from them. `make app` regenerates it and fails if the checked-in
// copy differs, so a protocol change breaks both builds at once instead of
// silently corrupting a patch on real hardware.

export const CLOCK_DEFAULT_BPM = 120;
export const CLOCK_MAX_BPM = 300;
export const CLOCK_MIN_BPM = 20;
export const CLOCK_SUBTICK = 24;
export const DRUM_SEQ_LANES = 8;
export const EEPROM_BYTES = 4284;
export const GPIO_N = 8;
export const MASTER_PPQN = 24;
export const MAX_IN = 5;
export const MAX_OUT = 8;
export const MAX_SEQUENCE_LEN = 32;
export const MIDI_CONTROL_PORT = 8;
export const N_CC_MAP = 32;
export const N_CV_BUS = 8;
export const N_GATE_BUS = 16;
export const N_MIDI_IN_NODES = 4;
export const N_MIDI_OUT_NODES = 4;
export const N_NODE = 32;
export const N_NOTE_BUS = 8;
export const N_PARAM = 336;
export const NO_BUS = 255;
export const NOTE_SEQ_VOICES = 4;
export const NRPN_CLOCK_BASE = 10752;
export const NRPN_RESERVED_BASE = 10784;
export const NRPN_TRANSPORT_BASE = 10768;
export const PATCH_FORMAT_VERSION = 2;
export const PATCH_MAGIC = 1296911683;
export const PATCH_SLOT_BYTES = 1071;
export const PATCH_SLOTS = 4;
export const SYSEX_BROADCAST_DEVICE = 127;
export const SYSEX_CHUNK_FIRST = 1;
export const SYSEX_CHUNK_LAST = 2;
export const SYSEX_CHUNK_PAYLOAD = 112;
export const SYSEX_DEFAULT_DEVICE = 0;
export const SYSEX_DEVICE_FAMILY = 1;
export const SYSEX_DEVICE_MEMBER = 1;
export const SYSEX_GENERAL_INFORMATION = 6;
export const SYSEX_IDENTITY_REPLY = 2;
export const SYSEX_IDENTITY_REQUEST = 1;
export const SYSEX_MANUFACTURER = 125;
export const SYSEX_PROTOCOL_VERSION = 2;
export const SYSEX_RX_MAX = 320;
export const SYSEX_TX_MAX = 320;
export const SYSEX_UNIVERSAL_NON_REALTIME = 126;

export const SysexCommand = Object.freeze({
  SYSEX_HELLO: 1,
  SYSEX_CAPS_REQUEST: 2,
  SYSEX_ALGO_REQUEST: 3,
  SYSEX_PARAM_REQUEST: 4,
  SYSEX_DUMP_REQUEST: 5,
  SYSEX_PATCH_CHUNK_IN: 6,
  SYSEX_PATCH_ABORT: 7,
  SYSEX_SET_PARAM: 16,
  SYSEX_GET_PARAM: 17,
  SYSEX_SET_CONNECTION: 18,
  SYSEX_SET_GATE_PORT: 19,
  SYSEX_SET_MIDI_PORT: 20,
  SYSEX_SET_GLOBALS: 21,
  SYSEX_SET_CC_MAP: 22,
  SYSEX_GET_CC_MAP: 23,
  SYSEX_CC_LEARN: 24,
  SYSEX_SET_NRPN: 25,
  SYSEX_SET_PATTERN: 26,
  SYSEX_GET_PATTERN: 27,
  SYSEX_GET_CONTROL: 28,
  SYSEX_SLOT_SAVE: 32,
  SYSEX_SLOT_LOAD: 33,
  SYSEX_SLOT_ERASE: 34,
  SYSEX_SLOT_LIST: 35,
  SYSEX_RESTORE_DEFAULTS: 48,
  SYSEX_IDENTITY: 65,
  SYSEX_CAPABILITIES: 66,
  SYSEX_ALGORITHM: 67,
  SYSEX_PARAM_DESC: 68,
  SYSEX_PATCH_CHUNK_OUT: 69,
  SYSEX_PARAM_VALUE: 81,
  SYSEX_CC_MAP: 82,
  SYSEX_PATTERN: 83,
  SYSEX_CONTROL_VALUE: 84,
  SYSEX_SLOTS: 99,
  SYSEX_ACK: 112,
  SYSEX_NAK: 113,
  SYSEX_EVENT: 114,
});

export const SysexError = Object.freeze({
  SYSEX_ERR_NONE: 0,
  SYSEX_ERR_BAD_VERSION: 1,
  SYSEX_ERR_TRUNCATED: 2,
  SYSEX_ERR_UNKNOWN_COMMAND: 3,
  SYSEX_ERR_BAD_ARGUMENT: 4,
  SYSEX_ERR_BAD_CHUNK: 5,
  SYSEX_ERR_TOO_LARGE: 6,
  SYSEX_ERR_BAD_IMAGE: 7,
  SYSEX_ERR_REJECTED: 8,
  SYSEX_ERR_NO_TRANSFER: 9,
  SYSEX_ERR_SLOT_EMPTY: 10,
  SYSEX_ERR_SLOT_CORRUPT: 11,
  SYSEX_ERR_BUSY: 12,
});

export const SysexEvent = Object.freeze({
  SYSEX_EVENT_PROGRAM_CHANGE: 1,
  SYSEX_EVENT_PATCH_APPLIED: 2,
  SYSEX_EVENT_ERROR: 3,
  SYSEX_EVENT_CC_LEARNED: 4,
});

export const MidiPort = Object.freeze({
  mmMIDI_USB_0: 1,
  mmMIDI_USB_1: 2,
  mmMIDI_USB_2: 4,
  mmMIDI_USB_3: 8,
  mmMIDI_SERIAL_1: 16,
  mmMIDI_SERIAL_2: 32,
  mmMIDI_SERIAL_3: 64,
  mmMIDI_HOST_1: 128,
});

export const CcTargetKind = Object.freeze({
  CC_TARGET_NODE: 0,
  CC_TARGET_CLOCK: 1,
  CC_TARGET_TRANSPORT: 2,
  CC_TARGET_PORT: 3,
  CC_TARGET_KINDS: 4,
});

export const CcClockTarget = Object.freeze({
  CC_CLOCK_TEMPO: 0,
  CC_CLOCK_SOURCE: 1,
  CC_CLOCK_PPQN: 2,
  CC_CLOCK_TARGETS: 3,
});

export const CcTransportTarget = Object.freeze({
  CC_TRANSPORT_START: 0,
  CC_TRANSPORT_STOP: 1,
  CC_TRANSPORT_CONTINUE: 2,
  CC_TRANSPORT_TAP: 3,
  CC_TRANSPORT_TARGETS: 4,
});

export const CcFlags = Object.freeze({
  CC_TAKEOVER_MASK: 3,
  CC_TAKEOVER_JUMP: 0,
  CC_TAKEOVER_PICKUP: 1,
  CC_TAKEOVER_SCALE: 2,
  CC_RELATIVE_MASK: 12,
  CC_ABSOLUTE: 0,
  CC_RELATIVE_TWOS: 4,
  CC_RELATIVE_SIGNED: 8,
  CC_RELATIVE_OFFSET64: 12,
  CC_FOURTEEN_BIT: 16,
  CC_PASS_THROUGH: 32,
});

export const GatePortDirection = Object.freeze({
  GATE_PORT_UNUSED: 0,
  GATE_PORT_IN: 1,
  GATE_PORT_OUT: 2,
});

export const ParamKind = Object.freeze({
  PARAM_NUMBER: 0,
  PARAM_ENUM: 1,
  PARAM_BOOL: 2,
  PARAM_BITFIELD: 3,
  PARAM_PITCH: 4,
  PARAM_PITCH_CLASS: 5,
  PARAM_SIGNED: 6,
  PARAM_MILLIS: 7,
  PARAM_PERCENT: 8,
  PARAM_CHANNEL: 9,
});

export const ConfigError = Object.freeze({
  CONFIG_OK: 0,
  CONFIG_UNKNOWN_ALGORITHM: 1,
  CONFIG_INLET_OUT_OF_RANGE: 2,
  CONFIG_INLET_NOT_CONNECTED: 3,
  CONFIG_OUTLET_OUT_OF_RANGE: 4,
  CONFIG_PARAM_OUT_OF_RANGE: 5,
});

export const AlgorithmId = Object.freeze({
  ALGO_NONE: 0,
  ALGO_LOGIC_NOT: 1,
  ALGO_LOGIC_AND: 2,
  ALGO_LOGIC_NAND: 3,
  ALGO_LOGIC_OR: 4,
  ALGO_LOGIC_NOR: 5,
  ALGO_LOGIC_XOR: 6,
  ALGO_LOGIC_XNOR: 7,
  ALGO_SUSTAIN: 8,
  ALGO_GATE_TO_NOTE: 9,
  ALGO_TRANSPOSE: 10,
  ALGO_ARPEGGIATOR: 11,
  ALGO_CLOCK_DIV: 12,
  ALGO_METRONOME: 13,
  ALGO_STEP_SEQ: 14,
  ALGO_EUCLID_SEQ: 15,
  ALGO_RANDOM_SEQ: 16,
  ALGO_NOTE_PRIORITY: 17,
  ALGO_VELOCITY: 18,
  ALGO_CHORD: 19,
  ALGO_NOTE_QUANTISE: 20,
  ALGO_PROBABILITY: 21,
  ALGO_NOTE_SEQ: 22,
  ALGO_POLY_SEQ: 23,
  ALGO_DRUM_SEQ_GATE: 24,
  ALGO_DRUM_SEQ_MIDI: 25,
});

export const ScaleId = Object.freeze({
  SCALE_GLOBAL: 0,
  SCALE_MAJOR: 1,
  SCALE_NATURAL_MINOR: 2,
  SCALE_HARMONIC_MINOR: 3,
  SCALE_MELODIC_MINOR: 4,
  SCALE_PENTATONIC_MAJOR: 5,
  SCALE_PENTATONIC_MINOR: 6,
  SCALE_BLUES: 7,
  SCALE_DORIAN: 8,
  SCALE_PHRYGIAN: 9,
  SCALE_LYDIAN: 10,
  SCALE_MIXOLYDIAN: 11,
  SCALE_LOCRIAN: 12,
  SCALE_WHOLE_TONE: 13,
  SCALE_CHROMATIC: 14,
  SCALE_COUNT: 15,
});

export const ScaleMask = Object.freeze({
  SCALE_GLOBAL: 0,
  SCALE_MAJOR: 2741,
  SCALE_NATURAL_MINOR: 1453,
  SCALE_HARMONIC_MINOR: 2477,
  SCALE_MELODIC_MINOR: 2733,
  SCALE_PENTATONIC_MAJOR: 661,
  SCALE_PENTATONIC_MINOR: 1193,
  SCALE_BLUES: 1257,
  SCALE_DORIAN: 1709,
  SCALE_PHRYGIAN: 1451,
  SCALE_LYDIAN: 2773,
  SCALE_MIXOLYDIAN: 1717,
  SCALE_LOCRIAN: 1387,
  SCALE_WHOLE_TONE: 1365,
  SCALE_CHROMATIC: 4095,
});

export const SysexErrorName = Object.freeze(Object.fromEntries(
  Object.entries(SysexError).map(([name, code]) => [code, name])));
export const ConfigErrorName = Object.freeze(Object.fromEntries(
  Object.entries(ConfigError).map(([name, code]) => [code, name])));
